apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-overlays
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/albertogd/gitops-for-organizations.git
      revision: develop
      files:
        - path: "clusters/**/cluster.json"
  template:
    metadata:
      name: "config-overlay-{{cluster.alias}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        targetRevision: develop
        path: clusters/{{environment}}/{{cluster.name}}/overlay
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy: {}
