apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-overlays
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/albertogd/gitops-for-organizations.git
      revision: develop
      files:
        - path: "clusters/**/conf.yaml"
  template:
    metadata:
      name: "config-{{cluster.environment}}-{{cluster.name}}-overlay"
    spec:
      project: default
      source:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        targetRevision: develop
        path: clusters/{{cluster.environment}}/{{cluster.fqdn}}/overlay
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy: {}
