apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-provisioning
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/albertogd/gitops-for-organizations.git
      revision: develop
      files:
        - path: "clusters/**/cluster.json"
  template:
    metadata:
      name: "provision-{{cluster.alias}}-cluster"
    spec:
      project: default
      source:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        targetRevision: develop
        path: base/templates/provision/openshift-provisioning
        helm:
          valueFiles:
            - /conf/{{environment}}/provision.yaml
            - /clusters/{{environment}}/{{cluster.name}}/provision.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 
      syncPolicy:
        preserveResourcesOnDeletion: true
