apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-cluster-config
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/albertogd/gitops-for-organizations.git
              revision: develop
              files:
                - path: "clusters/**/cluster.json"
          - list:
                - template: openshift-machine-config
                - template: openshift-ingress
                - template: openshift-marketplace
  template:
    metadata:
      name: "{{cluster.alias}}-cluster-config-{{template}}"
      labels:
        environment: "{{environment}}" 
        cluster: "{{cluster.name}}"
        region: "{{region}}"
        cloud: "{{cloud}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        targetRevision: develop
        path: . 
        plugin:
          name: kustomized-helm
          env:
            - name: HELM_TEMPLATES_BASE
              value: base/templates/config/{{template}}
            - name: CLUSTER_CONFIG_BASE
              value: clusters/{{cluster.name}}
            - name: ENVIRONMENT_CONFIG_BASE
              value: conf/"{{environment}}"
            - name: VALUES_FILE
              value: values.yaml
      destination:
        server: "{{cluster.address}}"
      syncPolicy: {}
