apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  annotations:
    helm.sh/hook-weight: "360"
  name: {{ .Values.cluster }}-worker
  namespace: {{ .Values.cluster }}
spec:
  clusterDeploymentRef:
    name: '{{ .Values.cluster }}'
  name: worker
  platform:
    vsphere:
      cpus: {{ .Values.workers.cpus }}
      coresPerSocket: {{ .Values.workers.coresPerSocket }}
      memoryMB: {{ .Values.workers.memoryMB }}
      osDisk:
        diskSizeGB: {{ .Values.workers.diskGB }}
  replicas: {{ .Values.workers.count }}
