apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster }}-ssh-private-key
  namespace: {{ .Values.cluster }}
stringData:
  ssh-privatekey: {{- .Values.provider.sshPrivatekey | toYaml | indent 2 }}
type: Opaque