apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-upgrade-cluster-411
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
