{{- if .Values.ingress.service.include }}

{{- range $domain := .Values.ingress.controller.domains }}

---
apiVersion: v1
kind: Service
metadata:
  name: router-nodeport-{{ $domain.name }}
  namespace: openshift-ingress
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: {{ $domain.name }}
    router: router-nodeport-{{ $domain.name }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: {{ $domain.http_port }}
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: {{ $domain.https_port }}
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: {{ $domain.name }}

{{- end }}

{{ end }}
