apiVersion: v1
data:
  operators-image.yml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      name: operators-disconnected
    spec:
      repositoryDigestMirrors:
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: quay.io
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: registry.redhat.io
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: registry.access.redhat.com
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: registry.connect.redhat.com
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: registry.hub.docker.com
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: nvcr.io
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: mcr.microsoft.com
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: gcr.io
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: registry.marketplace.redhat.com
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: docker.io
      - mirrors:
        - {{ .Values.imageContentSources.registry }}
        source: cp.icr.io
kind: ConfigMap
metadata:
  name: {{ .Values.cluster.name }}-image-content-sources
  namespace: {{ .Values.cluster.name }}

