apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    helm.sh/hook-weight: "360"
  name: {{ .Values.cluster }}
  namespace: {{ .Values.cluster }}
spec:
  clusterName: {{ .Values.cluster }}
  clusterNamespace: {{ .Values.cluster }}
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
