apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-vsphere-certs
  namespace: {{ .Values.cluster.name }}
stringData:
  .cacert: {{- .Values.provider.cacertificate | toYaml | indent 2 }}
type: Opaque
