apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster }}-vsphere-creds
  namespace: {{ .Values.cluster }}
stringData:
  username: {{ .Values.provider.username }} 
  password: {{ .Values.provider.password }}
