cluster:
  name: development
  domain: sandbox2710.opentlc.com
  fqdn: development.sandbox2710.opentlc.com
  address: "https://api.development.sandbox2710.opentlc.com:6443"
  environment: dev
  cloud: aws
  region: us-west-1
#  registry: quay-dev.io


  - ip-10-0-172-117.us-west-1.compute.internal
  - ip-10-0-207-60.us-west-1.compute.internal	
  - ip-10-0-221-41.us-west-1.compute.internal

#catalogSource:
#  rh_catalog_version: v4.10

#ingress:
#  controller:
#    syslog:
#      address: 10.9.0.1
