{{- if .Values.Ingress.Controller.include }}

{{- range $domain := .Values.Ingress.Controller.domains }}

---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: {{ $domain.name }}
  namespace: openshift-ingress-operator
spec:
  domain: {{ $domain.name }}.apps.{{ $.Values.Cluster.name }}.{{ $.Values.Cluster.domain }}
  
  endpointPublishingStrategy:
    type: NodePortService
  
  logging:
    access:
      destination:
        syslog:
          address: {{ $.Values.Ingress.Controller.Syslog.address }}
          port: 10514
        type: Syslog

  nodePlacement:
    nodeSelector:
      matchLabels:
        {{ $domain.placement | default $.Values.Ingress.Controller.default.placement }}: ""
    tolerations:
    - effect: NoSchedule
      operator: Exists

  replicas: {{ $domain.replicas | default $.Values.Ingress.Controller.default.replicas }}

{{- end }}

{{ end }}
